### ISSUE TITLE
Game Closes after starting a new Multiplayer Game 69 Mods

### ISSUE THREAD

**Issue by zwei7** [Pathoschild/SMAPI#783] opened 2021-06-05 19:17 UTC
**Game Exits**
Game turns itself off (the game closes/exits/alt-f4s itself)

**To Reproduce**
1. Load game with Mods (This 69 Mods)
2. Click CO-OP
3. Create a farmer with the name, farm name, and favorite thing as "1" and skip intro
4. Game Exits

**Log file**
https://smapi.io/log/9ed948ab63d8470d9134b8bd8f446f53

**Comment by Pathoschild** [comment] 2021-06-10 23:52
This seems to be a duplicate of #783 and #784.

**Closed as completed by Pathoschild** 2021-06-10 23:52 UTC
Labels: not a dev task
