### ISSUE TITLE
Migrate mod translation to general resource pipeline

### ISSUE THREAD

**Issue by lycc193** [Pathoschild/SMAPI#955] opened 2024-06-08 19:27 UTC
In the original game, all i18n-related content was loaded into the resource pipeline through LocalizedContentManager.LoadString -> Load<Dictionary<string, string>>(assetName) for subsequent reading.

However, in SMAPI, there are **only two ways** to load language files:
- Initialize mod: SCore.LoadMods -> SCore.ReloadTranslations -> Load mod/i18n/locale.json
- reload command: ReloadI18nCommand -> SCore.ReloadTranslations -> Load mod/i18n/locale.json

Apart from these, all calls to translations are **read-only**, retrieving target values from a list maintained by smapi using keys, rather than reading from the resource pipeline.

In the OnLocaleChanged event, translations are also treated differently. Other resources are redirected through the resource pipeline via suffixes.

**Comment by Pathoschild** [comment] 2024-06-09 03:48
Hi! As discussed in #954:

1. Mods can add translations as a content asset (just like any other data), in which case content packs can edit them.
2. If they don't do that, internal mod data can't be directly edited by other mods (including translations). This is currently by design; if you want to change that, see the next point.
3. GitHub issues are not the place for proposal discussions, since very few players and mod authors watch these issues. This is clearly indicated by the issue creation template you see when creating an issue. Instead you can discuss proposals in [#making-mods-general on Discord](https://smapi.io/community#Discord), where many others can join the discussion too.

To reiterate, **please discuss proposals in [#making-mods-general on Discord](https://smapi.io/community#Discord) where other mod authors can provide feedback too**. Any further proposals for this on GitHub issues will be closed as duplicate of the existing discussion.

**Closed by Pathoschild** 2024-06-09 03:48 UTC
Labels: duplicate

**Comment by lycc193** [comment] 2024-06-09 04:55
I've gone through ```https://stardewvalleywiki.com/Modding:Modder_Guide```, ```https://github.com/Pathoschild/StardewMods/blob/develop/ContentPatcher/docs/author-guide.md```, and the source code of SMAPI, but I couldn't find any mention of adding translations as content assets. Could you please clarify where you meant by this? 
I'm referring to the translations for mods, not the original game's translations.

**Comment by lycc193** [comment] 2024-06-09 05:04
Treating mod translation files differently is a functional deficiency of SMAPI. 
On Discord, I haven't seen any channels dedicated to discussing SMAPI itself. All discussions regarding translation files seem to be based on the original game's translations. 
While this current distinction does not affect mod creators, it can significantly impact mod translators. Similarly, I haven't found any Discord channels discussing mod translations.
