### ISSUE TITLE
Crashing with terminal modes that don't support color

### ISSUE THREAD

**Issue by LeonBlade** [Pathoschild/SMAPI#206] opened 2016-12-28 11:12 UTC
Recently a user that joined the Discord had a problem where they were getting a Null exception while trying to install or run the StardewModdingAPI executable.  The line in question is `Console.ForegroundColor` and it results in the variable `format` being null and triggering a null exception.

The stack trace points back to here:
https://github.com/Pathoschild/SMAPI/blob/b75d86e7cc19f9bc961abb475f22e8f2b059533c/src/StardewModdingAPI/Framework/Monitor.cs#L113

Or any of the four uses in the installer like here:
https://github.com/Pathoschild/SMAPI/blob/b75d86e7cc19f9bc961abb475f22e8f2b059533c/src/StardewModdingAPI.Installer/InteractiveInstaller.cs#L309

For macOS (like this user was using) the answer is to set the "Declare terminal as" in "Advanced" tab of the selected Profile to be "xterm-256color" or anything with color.
![macOS Terminal Settings](http://i.imgur.com/S7dSCL0.png)

It's obviously desirable to have color in the terminal, but for cases like this most users won't have any idea what broke and how to fix it.  There are a few obvious solutions like adding a troubleshooting section in the install guide, or abstracting the `Console.ForegroundColor` used in various places with something that can catch this and default to a colorless mode.

Personally, I would opt for doing this in the code as it makes things easier for troubleshooting the end user, perhaps even outputting something in the terminal about not supporting color and even linking to a page where you can learn how to fix it.

Regardless, I figured that I'd create an issue for this as I can see this being a problem for people again in the future.

**Comment by Pathoschild** [comment] 2016-12-30 17:19
Hi @LeonBlade. Do you have an example of the displayed error?

**Comment by LeonBlade** [comment] 2016-12-30 22:55
Hey there @Pathoschild.  This is the error they sent me.
https://www.dropbox.com/s/sya5l90i4mx9g5m/Screenshot%202016-12-28%2002.16.40.tiff?dl=0

The error comes back from the color like I said earlier.

**Comment by Pathoschild** [comment] 2017-01-14 20:07
Tentatively fixed in `develop` for the upcoming 1.6 release, but I can't test it myself since I don't have Mac. I'll keep this open until the beta is available and someone can confirm.

**Comment by Pathoschild** [comment] 2017-01-14 21:00
Fix confirmed with @LeonBlade. Thanks!

**Closed as completed by Pathoschild** 2017-01-14 21:00 UTC
Labels: bug
